### ISSUE TITLE
Google::Ads::Common::ReportDownloadError always returns false when tested for 'truthiness'

### ISSUE THREAD

**Issue by mcmillhj** [googleads/googleads-perl-lib#18]
Google::Ads::Common::ReportDownloadError is the object that is returned when an error occurs while pulling a report. The issue we are having is that:

This object always returns false when executed as a boolean statement using Class::Std's [BOOLIFY](https://github.com/googleads/googleads-perl-lib/blob/master/lib/Google/Ads/Common/ReportDownloadError.pm#L39) attribute

This is non-intuitive because it hides the fact that we got an error object as a response. In the example code below we would never know that `$response` was an object  because it looks like it is nothing: 

```
my $handler = Google::Ads::Common::ReportUtils::get_report_handler(
      $call_args->{report_definition}, 
      $self->gapi_client->get_google_client 
);
my $response = $handler->save( $call_args->{filename} );
if ( $response ) {
    process_response($response);
}
else {
    die "Did not get a response";
}
```

A possible solution is to instead use the [`:STRINGIFY`](https://metacpan.org/pod/Class::Std#STRINGIFY) attribute from Class::Std and stringify the ReportDownloadError object to type of error that was received:

```
sub as_str : STRINGIFY {
    my ($self) = @_;
    
    return join(' ', 
        $self->get_response_code(),
        $self->get_response_message(),
        $self->get_type(),
    ); 
}
```

This would return true when tested as a boolean, as well as allow pattern matching against the response.

**Comment by sundquist** [comment]
Greetings!

That is an interesting suggestion. I need to run through all the use cases where people are using this to make sure that I'm not breaking someone unintentionally. I think all our errors currently return false. If I  make the change, then I would want to be consistent across the entire library. Thanks again for the feedback!

Thanks,
Nadine Sundquist, AdWords API Team

**Comment by sundquist** [comment]
Hello,

Quite a few people rely on the **BOOLIFY** value coming back as false for errors, which is why I hesitate to make a change there. However, I can totally see **STRINGIFY** being useful for pattern matching when the error does come back. In order to allow you to pattern match, I added **STRINGIFY** in addition to **BOOLIFY** to our errors, such as [ReportDownloadError](https://github.com/googleads/googleads-perl-lib/blob/839dd87395484d963ba0ca5215b712cb875d6c62/lib/Google/Ads/Common/ReportDownloadError.pm), in version [4.11.0](https://github.com/googleads/googleads-perl-lib/releases/tag/v4.11.0) of the library. That matches a precedent set in some of our older custom errors in which we provide **STRINGIFY**.

Thanks for the suggestion. That will definitely make it easier for parsing an error quickly.

Cheers,
Nadine Sundquist, AdWords API Team
