### ISSUE TITLE
oAuth2ServiceAccountDelegateEmail should be oAuth2ServiceAccountDelegateEmailAddress

### ISSUE THREAD

**Issue by webtoolbox** [googleads/googleads-perl-lib#21]
On https://github.com/googleads/googleads-perl-lib/wiki/API-access-using-own-credentials-(server-to-server-flow), oAuth2ServiceAccountDelegateEmail should be oAuth2ServiceAccountDelegateEmailAddress.

**Comment by sundquist** [comment]
Greetings!

Thank you for taking the time to point that out. I must have fixed in my code, but missed it in the documentation. I just fixed it. I really hope it didn't cause you too much trouble. I'm glad you're such a good citizen to help the next person.

Thanks,
Nadine Sundquist, AdWords API Team
