### ISSUE TITLE
Refresh token suddenly not working after one day

### ISSUE THREAD

**Issue by webtoolbox** [googleads/googleads-perl-lib#22]
Since you resolved the other issue I raised so quickly, I thought I'd also let you know about this. We had an OAuth refresh token generated and working great with this perl library for over a year. When we upgraded to the latest version of this library, the refresh token suddenly stopped working and started returning this error:
[Fri Jan 26 15:47:57 2018] Died - {
 "error": "invalid_token",
 "error_description": "Invalid Value"
}

So, multiple times, we followed the instructions to generate a new refresh token. It worked with the new refresh token for 1 day. Then suddenly the refresh token stopped working again and gave the same error! (Even though all Google documentation says that the refresh token is *never* supposed to expire!) We tried the same process about 4 times before giving up and using the JSON file approach instead. The JSON file approach works without any issues.

Again, Important notes: 
1. This never happened before and only started happening after upgrading the library.
2. Google OAuth refresh tokens are never supposed to expire.
3. The refresh token does work for one day and then suddenly stops working, so the process to generate the refresh token is in fact being done properly. (We successfully see a conversion uploaded to adwords in our logs.)

**Comment by sundquist** [comment]
Hello,

I'm pleased to hear that you were able to at least get things working with JSON. I can see that one bump in the road doesn't deter you. 

You're right. Refresh tokens don't just expire. The only times I've seen refresh tokens no longer work is if more than 25 refresh tokens were generated (with the oldest refresh token no longer being viable) or if the refresh token was actively revoked. Based on how you've been using it, that doesn't sound like it's the case here. That error actually pops up when there's an issue with the access token and not the refresh token, so it's interesting to me that it worked when you regenerated another refresh token. 

I do have a few questions that may help me narrow down if one of my code changes triggered a change in behavior as I haven't seen it in my environment, and I haven't heard any other reports of this, yet. Perhaps, you have a slightly different setup that may be triggering this.
- What version of the library were you using before 5.0.0? 
- Were you putting everything including the refresh token into adwords.properties?
- Did you make any other changes at the same time?
- Did you change API versions at the same time?

Thanks,
Nadine, AdWords API Team

**Comment by sundquist** [comment]
Hi,

Just to keep everything on one thread, I'm going to respond here. As to solve your "You can't comment at this time", there are 3 possible ways I've heard of for solving that:
- If you have Adblocker installed, then disable it for GitHub. I've found this is the most common reason.
- If that doesn't work, refresh the page.
- If that doesn't work, log out and back into GitHub.
I want to keep this down to one issue since it could be kind of scary if we had to open a lot of issues just to respond back and forth,

I have one follow-up clarification question. When it comes to what client library you were using before 5.0.0. What version of the library were you using? Was it 4.18.0, 4.17.0, or some other earlier version?

As for my last question, you got it correct. I meant what API version as in v201702. My first question was around the client library version, which is which one you downloaded from GitHub or CPAN.

Thanks,
Nadine, AdWords API Team

P.S. I'm crossing my fingers over here that the Adblocker trick lets you reply on this thread.

**Comment by webtoolbox** [comment]
Unfortunately, I'm not sure what client library we were using before that. We just upgrade the module when we receive an email from Google saying that we should upgrade, so it is very likely to be the previous version before this latest one.

**Comment by sundquist** [comment]
Hello,

You were able to get the reply to work. Woot! I take joy in the small victories in life. Now on to serious business.

I have a huge favor to ask. I'm having difficulty reproducing this on my side as I'm using adwords.properties with this newer version and a refresh token. I've even pulled down the code base from scratch just to be sure. Would you happen to have a customer ID in the format of XXX-XXX-XXXX of one of the accounts where you've made a call recently and on the old version? That way I can mine our logs for a request where it worked and where it failed to see what the difference may be.

Thanks,
Nadine, AdWords API Team

**Comment by webtoolbox** [comment]
Yes! Turning off the ad blocker worked.

The customer ID is 692-745-6890.

**Comment by sundquist** [comment]
Hi,

Thanks for providing that customer ID. With that ID, I was able to walk through all the logs we have and determine the version of the client library that you were using before 5.0.0. Based on what I'm observing, it seems highly likely that you may have been setting your access token somewhere, and it was picking up the access token rather than picking up the refresh to generate a new access token each hour. There are a couple of possibilities. The most likely one I can think of is that perhaps in **adwords.properties** you had the **oAuth2AccessToken** property set. In that case, I can reproduce what you were seeing, and it matches what I see in the logs. Is that a possibility?

Cheers,
Nadine, AdWords API Team

**Comment by sundquist** [comment]
Hello,

It's me again. I was thinking I probably should add one more thing to try to save us a bit of time here. Based on my analysis, there's an experiment you could try out. You could try commenting out the **oAuth2AccessToken** in your **adwords.properties**, and only make sure that **oAuth2RefreshToken** is uncommented with the last refresh token you created. Also make sure other types of authentication such as JSON are commented out, so there's no confusion. See if that works. If not, please get back to me.

Thanks,
Nadine, AdWords API Team

**Comment by webtoolbox** [comment]
Hi Nadine,

Yes, that is what happened. It doesn't say anywhere in any documentation that oAuth2AccessToken shouldn't be set when using oAuth2RefreshToken. In fact, on this link:
https://github.com/googleads/googleads-perl-lib/wiki/API-access-using-own-credentials-(installed-application-flow)

It says "The following are the keys you can replace in your adwords.properties configuration:" and it lists oAuth2AccessToken as one of the things that should be replaced in adwords.properties, indicating that it should be in there.

**Comment by sundquist** [comment]
Greetings!

I am doing a bit of a happy dance over here! There is a logical explanation. You are totally right. That documentation can totally be better. I just fixed it to explain all of that. Thank you for bearing with me and providing that information.

I do need help from other people to point things like this out. I've been working with this client library for a number of years, so it feels like home to me, and things like the properties file are just like furniture. Over time, I just know where all the furniture in my client library house is, and I realize that guests sometimes bump into my furniture because they are not dealing with this everyday. I want to make sure that you feel just as at home in my client library as I do, so feel free to provide feedback when you bump into any more awkward furniture....I mean, issues. 

Take care,
Nadine, AdWords API Team
