### ISSUE TITLE
Remove XML::Simple

### ISSUE THREAD

**Issue by JRaspass** [googleads/googleads-perl-lib#24]
I first opened this bug on RT as that's what metacpan has listed as the bugtracker, but this issue list seems more responsive, which one is the right one? You might want to update your meta info if you prefer this one.

XML::Simple is only used for one feature in one file, __extract_xml_error in Google::Ads::AdWords::Utilities::BatchJobHandler - https://metacpan.org/source/SUNDQUIST/Google-Ads-AdWords-Client-5.1.0/lib/Google/Ads/AdWords/Utilities/BatchJobHandler.pm#L420

Given we already depend on the very decent XML::LibXML replacing XML::Simple with a new dep of https://metacpan.org/pod/XML::LibXML::Simple should provide the exact same functionality with far less crazy.

There seems to be a general movement to remove XML::Simple from CPAN modules, this is the AWS bug for instance - https://github.com/pplu/aws-sdk-perl/issues/66

My motivation is that at work this is the only module we use that still brings in XML::Simple.

I'm happy to actually write a patch and run the tests but I thought I'd submit a bug first to gauge interest.

**Comment by sundquist** [comment]
Hello,

Thanks for calling me out on those issues on RT. I stopped getting emails from them when issues came in awhile ago, and I didn't notice while GitHub still notifies me. So, I've been pretty active over here. Now that I know I have a backlog over there, I'll go take care of that. 

Yes, I am indeed trying to move towards XML::LibXML. Rather than just shifting to it right away (since it was so massive a change), I was trying to move the library in pieces to make sure we stayed stable. As you've probably noticed, the performance is a lot better, so I think it's worth moving everything over. I don't know if I can get it into the next release of the library, but I will look into it and keep this bug updated.

Cheers,
Nadine, AdWords API Team

**Comment by BenRKarl** [comment]
Closing this as this repo will be archived and all Perl users should (if not already) migrate to the new [library](https://github.com/googleads/google-ads-perl) for the [Google Ads API](https://developers.google.com/google-ads/api/docs/client-libs/perl).
